name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x

      - name: Restore dependencies
        run: dotnet restore TinyState.sln

      - name: Build
        run: dotnet build TinyState.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test TinyState.sln --configuration Release --no-build --verbosity normal
